services:
  zalo-tools-api:
    image: registry.iolis.solutions/iolis-mednova/landingpage:1.0
    container_name: zalo-tools-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    volumes:
      # Mount uploads directory for temporary file storage
      - uploads_data:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: iolis-network
    external: true

volumes:
  uploads_data:
